// import { ResizeDirection } from '@kit.TestKit';
// import { Font } from '@ohos.arkui.UIContext';
//
//
// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello 如影随形';
//
//   build() {
//     Column(){
//       Text('各种菜系')
//         .width('100%')
//         .height(40)
//         .fontSize(24)
//         .fontWeight(FontWeight.Bold)//或者直接数字100-900，默认400加粗700
//         .backgroundColor(Color.Brown)
//       Row(){
//         Text('java')
//           .width(60)
//           .height(30)
//           .backgroundColor(Color.Red)
//         Text('C++')
//           .width(60)
//           .height(30)
//           .backgroundColor(Color.Orange)
//         Text('Hmos')
//           .width(60)
//           .height(30)
//           .backgroundColor(Color.Green)
//         Text('Python')
//           .width(60)
//           .height(30)
//           .backgroundColor(Color.Blue)
//       }
//       .width('100%')
//       .backgroundColor(Color.Orange)
//     }
//
//   }
// }