// import { ResizeDirection } from '@kit.TestKit';
// import { Font } from '@ohos.arkui.UIContext';
//
//
// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello 如影随形';
//
//   build() {
//     //今日头条置顶思路：排版，内容，美化
//     Column(){
//       Text('学鸿蒙，就来黑马程序员~')
//         .width('100%')
//         .height(40)
//         .fontSize(24)
//       Row(){
//         Text('置顶  ')
//           .fontColor('#df3c50')
//         Text('新华社  ')
//           .fontColor('#a1a1a1')
//         Text('2260评论')
//           .fontColor('#a1a1a1')
//
//       }
//       .width('100%')
//
//     }
//     .width('100%')
//
//   }
// }