// import { ResizeDirection } from '@kit.TestKit';
// import { Font } from '@ohos.arkui.UIContext';
//
//
// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello 如影随形';
//   build() {
//     Column(){
//       Image($r('app.media.avatar'))
//         .width(200)
//       Text('如影随形')
//         .width(200)
//       Row(){
//         Image($r('app.media.guimie'))
//           .width(20)
//         Text('我妻善逸')
//       }
//       .width(200)
//     }
//   }
// }