// import { ResizeDirection } from '@kit.TestKit';
// import { Font } from '@ohos.arkui.UIContext';
//
//
// @Entry
// @Component
// struct Index {
//   @State message: string = 'Hello 如影随形';
//
//   build() {
//     //svg：任意放大缩小不失真，可以修改颜色
//     Column(){
//       Text('杨过')
//         .backgroundColor(Color.Pink)
//         .padding({
//           left:20,
//           right:20,
//           top:30,
//           bottom:40
//         })
//       Text('小龙女')
//         .backgroundColor(Color.Orange)
//         .margin({
//           top:30,
//           bottom:50
//         })
//       Text('杨幂')
//         .backgroundColor(Color.Blue)
//         .padding(30)
//
//       Row(){
//         Text('杨过')
//           .backgroundColor(Color.Pink)
//           .padding({
//             left:20,
//             right:20,
//             top:30,
//             bottom:40
//           })
//         Text('小龙女')
//           .backgroundColor(Color.Orange)
//           .margin({
//             top:30,
//             bottom:50
//           })
//         Text('杨幂')
//           .backgroundColor(Color.Blue)
//           .padding(30)
//
//       }
//     }
//
//   }
// }